version: "3.7"
services:
  mqtt:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
