mqtt:
  broker:
    url: tls://2e0cec621e954a97b4917df783269b7e.s2.eu.hivemq.cloud:8883
    username:
    password:

sensor:
  airportIATA: DXB
  deviceId: 123e4567-e89b-12d3-a456-426655440000
  sensorType: temperature
  frequency: 2

api:
  url: http://api.weatherstack.com/current?access_key=%s&query=%s
  secretKey:
