name: ${NAME:mqtt2mongodb}

datasource:
  url: ${MONGODB_URL:mongodb://localhost:27017}
  username: ${MONGODB_USERNAME:}
  password: ${MONGODB_PASSWORD:}

mqttBroker:
  url: ${MQTT_URL:tcp://localhost:1883}
  username: ${MQTT_USERNAME:}
  password: ${MQTT_PASSWORD:}
  topic: ${MQTT_TOPIC:}

web:
  port: ${WEB_PORT:8080}