file:
  path: "C:\Users\cleme\OneDrive\Documents\cours\architechtures_distribuees\golang\Airport_MQTT\records"

mqtt:
  broker:
    url: tcp://localhost:1883
    username:
    password:
  client:
    id: file_recorder